language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"
before_install:
  - pip install -U pip
  - pip install codecov
  - pip install -U pytest
install:
  - pip install -U -r requirements/travis.txt
  - pip install -e .
script:
  - pytest --cov
after_success:
  - codecov